Repository EternalReturnInfo/EternalReuturnInfo, pull requests merged in 2023-11, with the labels that each got.

#46 [CHAT]: 채팅목록 가져오는 방법 수정 ( From 듀오, 게시판 )
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/erionna/eternalreturninfo/model/ERModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/model/Message.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/ChatActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/intro/.gitkeep
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/ChatListAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindDuoFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/ChatListViewModel.kt
  app/src/main/res/drawable/chat_submit_btn_background.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_back2.xml
  app/src/main/res/drawable/ic_new_chat_blue.png
  app/src/main/res/drawable/ic_new_message.png
  app/src/main/res/drawable/ic_new_message2.png
  app/src/main/res/drawable/ic_new_msg_3.png
  app/src/main/res/drawable/ic_new_msg_4.png
  app/src/main/res/drawable/ic_new_msg_5.png
  app/src/main/res/drawable/ic_new_msg_6.png
  app/src/main/res/drawable/ic_new_msg_7.png
  app/src/main/res/layout/chat_activity.xml
  app/src/main/res/layout/chat_item_receiver.xml
  app/src/main/res/layout/chat_item_sender.xml
  app/src/main/res/layout/chat_list_fragment.xml
  app/src/main/res/layout/chat_list_item.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/values/strings.xml
Labels: DESIGN🎨, FEATURE⚙️, COMPLETION🎉

#53 [BOARD] : 조건별 공지 카테고리 표시
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/BoardSingletone.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/SignUpPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/board/BoardAdd.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/board/BoardPost.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/board/BoardUpdate.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/board/BoardRecyclerViewAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MainFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/board/BoardFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/MainListViewModel.kt
  app/src/main/res/layout/chat_activity.xml
  app/src/main/res/layout/chat_list_fragment.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/values/board_array.xml
Labels: FEATURE⚙️

#55 [CHAT]: 채팅기능
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindDuoFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindduoAdapter.kt
  app/src/main/res/layout/chat_list_fragment.xml
  app/src/main/res/layout/login_activity.xml
Labels: DESIGN🎨, FEATURE⚙️, COMPLETION🎉

#58 Fix/findduo2
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/SignUpPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/findduo/FindduoAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindDuoFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindduoPopupWindow.kt
  app/src/main/res/drawable/shape_findduo_remove_dialog.xml
  app/src/main/res/layout/findduo_remove_dialog.xml
Labels: DESIGN🎨, FEATURE⚙️, FIX🔧

#59 [CHAT] : 코드정리
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/chat/ChatActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/SignUpPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/chat/ChatAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/chat/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/ChatListViewModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/ChatViewModel.kt
Labels: REFACTOR♻️

#60 [MYPROFILE] : 디자인 변경
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/board/BoardSearch.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/myprofile/MyProfileViewPagerAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/board/BoardFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileBoardFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment2.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyprofileRecordFragment.kt
  app/src/main/res/drawable/shape_myprofile_drawable_selected_tab.xml
  app/src/main/res/drawable/shape_myprofile_drawable_unselected_tab.xml
  app/src/main/res/drawable/tab_board_selector.xml
  app/src/main/res/drawable/tab_myprofile_selector.xml
  app/src/main/res/layout/board_fragment.xml
  app/src/main/res/layout/board_search_activity.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/myprofile_fragment.xml
  app/src/main/res/layout/myprofile_fragment2.xml
  app/src/main/res/layout/myprofile_item_recyclerview.xml
  app/src/main/res/layout/myprofile_record_fragment.xml
  app/src/main/res/values/strings.xml
Labels: DESIGN🎨

#62 [BOARD] : 게시판 튕기는 문제
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/board/BoardAskFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/board/BoardDailyFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/board/BoardNoticeFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/board/BoardTipsFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/board/BoardTotalFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment2.kt
  app/src/main/res/layout/myprofile_fragment2.xml
  app/src/main/res/layout/myprofile_record_fragment.xml
Labels: FIX🔧

#63 [Findduo] : null 값 오류
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/LoginPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindDuoFragment.kt
  app/src/main/res/layout/login_activity.xml
Labels: bug, FIX🔧

#64 [CHAT] : 팝업메뉴 디자인 수정
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/board/BoardAdd.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/board/BoardPost.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/chat/ChatActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/LoginPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/SignUpPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/board/BoardCommentRecyclerViewAdpater.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/main/MainViewPagerAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/chat/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/ChatListViewModel.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
  settings.gradle.kts
Labels: DESIGN🎨, FEATURE⚙️

#66 [FEATURE] : 팝업메뉴 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/board/BoardPostActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/board/BoardCommentRecyclerViewAdpater.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment.kt
Labels: FEATURE⚙️, COMPLETION🎉

#69 [MYPROFILE] : 탭메뉴 사이즈 조정 및 모션토스트 적용
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment.kt
Labels: DESIGN🎨, PACK🎁

#70 [PACK] : myfrofile 비밀번호변경 사이즈 조정 및 모션토스트 적용
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/myprofile/MyProfileFragment.kt
Labels: DESIGN🎨, PACK🎁

#71 [FINDDUO] : 듀오수 스타일 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/find_duo_fragment.xml
Labels: DESIGN🎨, COMPLETION🎉

#72 [FINDDUO] : 듀오 수 TextView 스타일 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/find_duo_fragment.xml
Labels: COMPLETION🎉

#73 [MAIN] : Youtube API 키 숨기기
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/erionna/eternalreturninfo/util/Constants.kt
Labels: FIX🔧

#74 [MAIN] : API키 숨기기
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/erionna/eternalreturninfo/util/Constants.kt
Labels: COMPLETION🎉

#75 [MYPROFILE] : viewpager2 잘리는 오류 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/LoginActivity.kt
  app/src/main/res/layout/myprofile_board_rv_fragment.xml
  app/src/main/res/layout/myprofile_fragment.xml
  app/src/main/res/layout/myprofile_item_recyclerview.xml
  app/src/main/res/layout/myprofile_record_fragment.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: FIX🔧

#76 [MYPROFILE] : viewpager2 잘리는 오류 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/LoginActivity.kt
  app/src/main/res/layout/myprofile_board_rv_fragment.xml
  app/src/main/res/layout/myprofile_fragment.xml
  app/src/main/res/layout/myprofile_item_recyclerview.xml
  app/src/main/res/layout/myprofile_record_fragment.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: FIX🔧

#77 [LOGIN] : 비밀번호 찾기 토스트 내용 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/LoginActivity.kt
  app/src/main/res/layout/board_fragment.xml
  app/src/main/res/layout/myprofile_fragment.xml
  app/src/main/res/values/themes.xml
Labels: bug, DESIGN🎨

#78 [PACK] : 비밀번호 찾기 토스트 메시지 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/login/LoginActivity.kt
  app/src/main/res/layout/board_fragment.xml
  app/src/main/res/layout/myprofile_fragment.xml
  app/src/main/res/values/themes.xml
Labels: bug, DESIGN🎨
