Repository EternalReturnInfo/EternalReuturnInfo, pull requests merged in 2023-10, with the labels that each got.

#6 [DESIGN] : 로그인페이지 UI 구현
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/LoginPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/SignUpPage.kt
  app/src/main/res/drawable/ic_black_logo.png
  app/src/main/res/drawable/ic_white_logo.png
  app/src/main/res/drawable/shape_login_btn.xml
  app/src/main/res/layout/activity_sign_up_page.xml
  app/src/main/res/layout/loginpage_activity.xml
  app/src/main/res/values/themes.xml
Labels: design

#9 [MAIN] : 레이아웃 완성
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/MainActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/SearchFragment.kt
  app/src/main/res/drawable/ic_xiuk.png
  app/src/main/res/drawable/shape_gary_btn.xml
  app/src/main/res/drawable/shape_highlight_btn.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/layout/main_recyclerview_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design🎨

#10 [CHAT] : 레이아웃 완성
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/erionna/eternalreturninfo/model/ERModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/ChatActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/ChatListAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/.gitkeep
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/ChatListViewModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/util/Constants.kt
  app/src/main/res/drawable/ic_character.jpg
  app/src/main/res/drawable/ic_jaekie.png
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/layout/chat_activity.xml
  app/src/main/res/layout/chat_fragment.xml
  app/src/main/res/layout/chat_list_fragment.xml
  app/src/main/res/layout/chat_list_item.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: design🎨

#12 [Board] : layout 디자인 완성
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/erionna/eternalreturninfo/model/BoardModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardAdd.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardPost.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/BoardCommentRecyclerViewAdpater.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/BoardRecyclerViewAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/BoardFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MainFragment.kt
  app/src/main/res/drawable/ic_board_arrow.xml
  app/src/main/res/drawable/ic_board_baseline_more_horiz_24.xml
  app/src/main/res/drawable/ic_board_comment.xml
  app/src/main/res/drawable/ic_board_visit_check.xml
  app/src/main/res/layout/board_add_activity.xml
  app/src/main/res/layout/board_fragment.xml
  app/src/main/res/layout/board_post_activity.xml
  app/src/main/res/layout/board_post_rv_comment_item.xml
  app/src/main/res/layout/board_rv_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design🎨

#13 [DESIGN] : BoardPage layout 디자인 완성
  app/src/main/res/drawable/ic_board_baseline_add_24.xml
  app/src/main/res/layout/board_add_activity.xml
  app/src/main/res/layout/board_post_rv_comment_item.xml
Labels: design🎨

#21 [Findduo] : 레이아웃 1차 완성
  app/src/main/res/drawable/ic_state_layer.png
  app/src/main/res/drawable/ic_white_logo.png
  app/src/main/res/drawable/ic_xiuk.png
  app/src/main/res/drawable/shape_gray_btn.xml
  app/src/main/res/drawable/shape_highlight_btn.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/layout/walk_through_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: DESIGN🎨

#30 [BOARD] : 게시판 기능 완성
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/erionna/eternalreturninfo/model/BoardModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/BoardSingletone.kt
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/FBRef.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardAdd.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardDeleted.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardDialog.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardPost.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardSearch.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardUpdate.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/BoardCommentRecyclerViewAdpater.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/BoardRecyclerViewAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/BoardFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/BoardListViewModel.kt
  app/src/main/res/drawable/ic_board_alert.png
  app/src/main/res/drawable/ic_board_cancel.png
  app/src/main/res/drawable/ic_board_plus.png
  app/src/main/res/drawable/ic_board_recycle_bin.png
  app/src/main/res/drawable/ic_board_search.png
  app/src/main/res/drawable/ic_state_layer.png
  app/src/main/res/drawable/shape_board_button.xml
  app/src/main/res/drawable/shape_board_dialog.xml
  app/src/main/res/drawable/shape_board_search.xml
  app/src/main/res/drawable/shape_gray_btn.xml
  app/src/main/res/layout/activity_board_update.xml
  app/src/main/res/layout/board_add_activity.xml
  app/src/main/res/layout/board_deleted_activity.xml
  app/src/main/res/layout/board_dialog.xml
  app/src/main/res/layout/board_fragment.xml
  app/src/main/res/layout/board_post_activity.xml
  app/src/main/res/layout/board_post_rv_comment_item.xml
  app/src/main/res/layout/board_search_activity.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/menu/menu_option_comment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: REFACTOR♻️

#31 [CHAT] : 채팅기능
  .gitkeep
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/erionna/eternalreturninfo/model/ERModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/model/Message.kt
  app/src/main/java/com/erionna/eternalreturninfo/model/User.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/ChatActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/ChatAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/ChatListAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/ChatListViewModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/viewmodel/ChatViewModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/util/Constants.kt
  app/src/main/res/drawable/ic_alonso.png
  app/src/main/res/drawable/ic_aya.png
  app/src/main/res/drawable/ic_daniel.png
  app/src/main/res/drawable/ic_felix.png
  app/src/main/res/drawable/ic_mai.png
  app/src/main/res/drawable/receiver_background.xml
  app/src/main/res/drawable/sender_background.xml
  app/src/main/res/layout/chat_activity.xml
  app/src/main/res/layout/chat_item_receiver.xml
  app/src/main/res/layout/chat_item_sender.xml
  app/src/main/res/layout/chat_list_fragment.xml
  app/src/main/res/layout/chat_list_item.xml
  app/src/main/res/layout/dialog_sign_in.xml
  app/src/main/res/layout/dialog_sign_up.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: COMPLETION🎉

#32 [FEAT] : 회원가입 시 리얼타임 데이터베이스 추가
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/erionna/eternalreturninfo/model/ERModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/model/SignUpData.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/LoginPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/MainActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/SignUpImagePage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/SignUpPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/ChatListAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MyProfileFragment.kt
  app/src/main/res/drawable/ic_character_01haze.png
  app/src/main/res/drawable/ic_character_02xiukai.png
  app/src/main/res/drawable/ic_character_03nadine.png
  app/src/main/res/drawable/ic_character_04nathapon.png
  app/src/main/res/drawable/ic_character_05nicty.png
  app/src/main/res/drawable/ic_character_06daniel.png
  app/src/main/res/drawable/ic_character_07tia.png
  app/src/main/res/drawable/ic_character_08laura.png
  app/src/main/res/drawable/ic_character_09lenox.png
  app/src/main/res/drawable/ic_character_10leon.png
  app/src/main/res/layout/activity_sign_up_page.xml
  app/src/main/res/layout/findpw_dialog.xml
  app/src/main/res/layout/google_dialog.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/myprofile_fragment.xml
  app/src/main/res/layout/signup_image_activity.xml
  app/src/main/res/layout/signup_information_activity.xml
  app/src/main/res/layout/signup_spinner.xml
  app/src/main/res/values/array.xml
  build.gradle.kts
Labels: FEATURE⚙️

#33 [CHAT] : 파이어베이스 통합
  README.md
  app/build.gradle.kts
  app/src/main/java/com/erionna/eternalreturninfo/model/BoardModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/BoardSingletone.kt
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/FBRef.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardAdd.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardDialog.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardPost.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/ChatActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/LoginPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/BoardCommentRecyclerViewAdpater.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/BoardRecyclerViewAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/ChatAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/ChatListAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/BoardFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/util/Constants.kt
  app/src/main/res/layout/board_add_activity2.xml
  app/src/main/res/layout/chat_list_fragment.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/main_fragment.xml
Labels: FEATURE⚙️

#34 [FEAT] : 마이페이지에서 프로필사진 변경기능 구현
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/erionna/eternalreturninfo/model/ERModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/model/User.kt
  app/src/main/java/com/erionna/eternalreturninfo/model/VideoModel.kt
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/RetrofitInstance.kt
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/YoutubeApiService.kt
  app/src/main/java/com/erionna/eternalreturninfo/retrofit/YoutubeVideo.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/LoginPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/MainActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/SignUpPage.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/intro/.gitkeep
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/intro/SplashActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MainAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MainFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MyProfileFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/WalkThroughFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindDuoFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindduoAdapter.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/signin/LoginActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/signup/SignUpActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/util/Constants.kt
  app/src/main/res/drawable/background_splash.xml
  app/src/main/res/drawable/border_background.xml
  app/src/main/res/drawable/shape_findduo_btn.xml
  app/src/main/res/drawable/shape_findduo_dialog.xml
  app/src/main/res/drawable/shape_gray_btn.xml
  app/src/main/res/drawable/shape_highlight_btn.xml
  app/src/main/res/drawable/shape_main_btn.xml
  app/src/main/res/drawable/shape_register_btn.xml
  app/src/main/res/layout/find_duo_dialog.xml
  app/src/main/res/layout/find_duo_fragment.xml
  app/src/main/res/layout/find_duo_list_item.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/login_activity2.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/layout/main_video_item.xml
  app/src/main/res/layout/myprofile_character_dialog.xml
  app/src/main/res/layout/myprofile_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/sign_up_activity.xml
  app/src/main/res/layout/sign_up_activity2.xml
  app/src/main/res/layout/splash_activity.xml
  app/src/main/res/layout/walk_through_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
Labels: FEATURE⚙️

#36 [DUO] : 리사이클러뷰 클릭이벤트
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/BoardPost.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/activity/MainActivity.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/ChatListFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MainFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MyProfileFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindDuoFragment.kt
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/findduo/FindduoAdapter.kt
  app/src/main/res/layout/find_duo_list_item.xml
  app/src/main/res/layout/main_fragment.xml
Labels: FEATURE⚙️

#39 [MYPROFILE] : 사용자 통계 연결
  app/src/main/java/com/erionna/eternalreturninfo/ui/fragment/MyProfileFragment.kt
  app/src/main/res/layout/myprofile_fragment.xml
Labels: FEATURE⚙️, FIX🔧
